version: 0.2

env:
  variables:
    GRADLE_HOME: /usr/local/gradle-4.8.1

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - command
      - cd /usr/local && \
        curl -L https://services.gradle.org/distributions/gradle-4.8.1-bin.zip -o gradle-4.8.1-bin.zip && \
        unzip gradle-4.8.1-bin.zip && \
        rm gradle-4.8.1-bin.zip
#      - export GRADLE_HOME=/usr/local/gradle-4.8.1
  pre_build:
    commands:
      - gradle test
  post_build:
    commands:
      - gradle build
      - echo $PWD
      - ls

artifacts:
  files:
    - '**/*'