version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - curl -L https://services.gradle.org/distributions/gradle-4.8.1-bin.zip -o /usr/local/gradle-4.8.1-bin.zip
      - unzip /usr/local/gradle-4.8.1-bin.zip
      - rm /usr/local/gradle-4.8.1-bin.zip
      - export GRADLE_HOME=/usr/local/gradle-4.8.1
  pre_build:
    commands:
      - gradle test
  post_build:
    commands:
      - gradle build

artifacts:
  files:
    - demo-0.0.1-SNAPSHOT.jar
  base-directory: 'build/libs'
  discard-paths: yes